#!/usr/bin/env python3
"""build_level_correct.py -- the corrected level-{N}.json builder.

Supersedes tada_level_builder.py's bitmap-based room numbering, which is
unsound: SPUR's own D.LEVEL{N}.TXT "populated room" bitmap is unreliable
(confirmed missing real, populated grid positions), and zipping decoded
messages against it in ascending order silently misaligns room numbers
for every level except level 2, where the counts happened to match by
luck. See ../server/LEVEL_AUDIT.md §17/§18 for the full investigation
that found and fixed this.

Combines the three correct pieces that investigation turned up:

  1. Direct positional room numbering: message directory position IS the
     true SPUR room number (message N lives at directory entry (N-1)*4 --
     confirmed against Source/Acos/DISK.S in
     https://github.com/callapple/GBBS/tree/master/Source, GBBS Pro's own
     6502 source), not anything derived from the header bitmap. Verified
     by exit self-consistency: 98.9-100% on 6 of 7 levels, and every
     remaining mismatch traced to a real, intentional SPUR mechanic (a
     fixed Bar-link special case, or a level-6 "Outer Space" room whose
     exit deliberately leads into an unbuilt grid cell) -- none are
     reconstruction errors.

  2. convert_from_gbbs_tool.py's parse_name_field/RoomFlag: the complete
     flag vocabulary. tada_level_builder.py's own copy of this parser is
     missing several real flags (no_comm_signal, all four
     vehicle_exit_*/vehicle_departure_* directions, hidden_door_*) that
     convert_from_gbbs_tool.py already has -- confirmed as "the real
     converter" by a past commit matching its flag vocabulary against the
     shipped level files.

  3. tada_level_builder.py's resolve_exit_destinations: SPUR's own
     wraparound-grid formula for turning raw 0/1 exit flags into real
     destination room numbers. Extended here to also resolve
     hidden_exit_east/west destinations automatically (force that one
     direction's raw flag on and reuse the same formula) -- verified
     against every hidden-exit room in level 6 against the exact same
     known-good pairings previously traced by hand in commit 2d7f1b8
     (matching item placements 132/134/138 and connector-room names
     precisely), so this is a mechanical derivation, not a new guess.

Usage:
    python3 build_level_correct.py <level_number>          # prints JSON to stdout
    python3 build_level_correct.py <level_number> --write   # writes ../server/level_{N}.json

Level 1 is deliberately excluded -- it was already built with real SPUR
room numbers by a separate, correct pipeline (convert_map_data.py) and
should not be regenerated by this script.

Known follow-up data patches this script does NOT (and cannot) derive,
carried forward from past manual work at their new real room numbers --
reapply these after regenerating if rebuilding levels 5 or 6:
  - level 5, room 223 "Tiny Meadow": 'grassy' flag (TADA retrofit, no
    SPUR precedent -- commit b12a0ba).
  - level 6, rooms 868/869 "Outer Space"/"Air Lock": connecting
    east/west exit (SPUR's raw data has none at all -- deliberate TADA
    bugfix, commit e584623).
  - level 5, room 157 "Rivertown": horse-paddock hint text (TADA
    addition, not from SPUR).
"""
import sys
import struct
import json
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
sys.path.insert(0, str(Path(__file__).parent / 'level-2'))
from tada_level_builder import LevelHeader, _follow_chain, resolve_exit_destinations
from convert_from_gbbs_tool import parse_name_field

EXIT_KEYS = ['north', 'south', 'east', 'west', 'rc', 'rt']


def extract_positional(room_file: Path) -> dict[int, str]:
    """Return {room_number: raw_message_text}, using directory position
    directly as the room number (entry_num + 1) -- SPUR's real addressing
    scheme, per Source/Acos/DISK.S's MSG routine. Skips non-decodable
    directory slots."""
    data = room_file.read_bytes()
    bitmap_blocks = data[0]
    dir_blocks    = data[1]
    dir_offset    = 8 + bitmap_blocks * 128
    data_offset   = dir_offset + dir_blocks * 128
    max_entries   = (dir_blocks * 128) // 4
    total_blocks  = (len(data) - data_offset) // 128

    pop = {}
    for entry_num in range(max_entries):
        entry_off = dir_offset + entry_num * 4
        if entry_off + 4 > len(data):
            break
        block_num = struct.unpack('<H', data[entry_off + 2:entry_off + 4])[0]
        if block_num == 0 or block_num > total_blocks:
            continue
        text = _follow_chain(data, block_num, total_blocks, data_offset)
        if text.strip():
            pop[entry_num + 1] = text
    return pop


def parse_room(room_no: int, text: str, ri: int, nr: int) -> dict | None:
    lines = [l for l in text.splitlines() if l.strip()]
    if not lines:
        return None
    parts = lines[0].split(',')
    if len(parts) < 11:
        return None
    raw_name = parts[0]
    try:
        monster = int(parts[1]); item = int(parts[2])
        weapon  = int(parts[3]); food = int(parts[4])
        exits_raw = {k: int(v) for k, v in zip(EXIT_KEYS, parts[5:11])}
    except (ValueError, IndexError):
        return None

    exits = resolve_exit_destinations(exits_raw, room_no, ri, nr)
    name, alignment, flags = parse_name_field(raw_name)
    desc = ' '.join(l.strip() for l in lines[1:] if l.strip())
    flag_values = [f.value for f in flags]

    room = {
        "number": room_no,
        "name": name,
        "room_alignment": alignment.value,
        "flags": flag_values,
        "exits": {k: v for k, v in exits.items() if v != 0},
        "monster": monster,
        "item": item,
        "weapon": weapon,
        "food": food,
        "desc": desc,
    }

    if 'hidden_exit_east' in flag_values:
        forced = dict(exits_raw); forced['east'] = 1
        room['hidden_exit_east'] = resolve_exit_destinations(forced, room_no, ri, nr)['east']
        flag_values.remove('hidden_exit_east')
    if 'hidden_exit_west' in flag_values:
        forced = dict(exits_raw); forced['west'] = 1
        room['hidden_exit_west'] = resolve_exit_destinations(forced, room_no, ri, nr)['west']
        flag_values.remove('hidden_exit_west')
    room['flags'] = flag_values

    return room


def build_level(header_file: Path, room_file: Path) -> tuple[LevelHeader, list[dict]]:
    hdr = LevelHeader.read(header_file)
    pop = extract_positional(room_file)
    rooms = []
    for room_no in sorted(pop):
        r = parse_room(room_no, pop[room_no], hdr.map_width, hdr.total_rooms)
        if r:
            rooms.append(r)
    return hdr, rooms


if __name__ == '__main__':
    if len(sys.argv) < 2:
        print(f"Usage: {sys.argv[0]} <level_number> [--write]", file=sys.stderr)
        sys.exit(1)

    n = int(sys.argv[1])
    if n == 1:
        print("Level 1 already has real SPUR room numbers -- do not regenerate it.", file=sys.stderr)
        sys.exit(1)

    spur_data = Path(__file__).parent
    header_file = spur_data / f'D.LEVEL{n}.TXT'
    room_file = None
    for pattern in (f'ROOM_LEVEL{n}.TXT', f'ROOM.LEVEL{n}.TXT'):
        candidate = spur_data / pattern
        if candidate.exists():
            room_file = candidate
            break
    if room_file is None:
        print(f"Could not find ROOM_LEVEL{n}.TXT or ROOM.LEVEL{n}.TXT", file=sys.stderr)
        sys.exit(1)

    hdr, rooms = build_level(header_file, room_file)
    print(f'level {n}: {hdr.title!r} grid={hdr.map_width}x{hdr.map_height} '
          f'rooms_written={len(rooms)}', file=sys.stderr)

    output = json.dumps({"rooms": rooms}, indent=4)
    if '--write' in sys.argv:
        out_path = spur_data.parent / 'server' / f'level_{n}.json'
        out_path.write_text(output)
        print(f'  wrote {out_path}', file=sys.stderr)
    else:
        print(output)
