; tile_demo_data.asm -- GENERATED by tiles/make_demo_map.py, don't edit.
; Source: Overworld.png, layout demo_map.json
; Shared colors: bg green, mc1 light green, mc2 light red
; 195 unique chars + the divider at $a0
MAP_W           = 80
MAP_H           = 48
MAP_BG          = 5
MAP_MC1         = 13
MAP_MC2         = 10
DIVIDER_CHAR    = $a0
